spring.application.name=real-time-chat-application

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/real_application?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Root@123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=9050

jwt.secretKey="305c300d06092a864886f70d0101010500034b0030480241009f51b8e9c08d6fe888144e285fe61843ba37befa0d757cbdc37d16fc15c74053615981d5bdaf2dd9ade3624104b0ba6bab0c2aa0503af9d7321bc67c17d46d590203010001"